### ISSUE TITLE
Bad URL?

### ISSUE THREAD

**Issue by variab1e** [lxr/go.google.musicmanager#1]
I am getting a 503 error (`: session error 503`) when I run Post to the given URL , example `https://uploadsj.clients.google.com/uploadsj/scottyagent?upload_id=AEnB2UrWAjqXgq2_EuRs_GooghDHZeY6xhIjnY2oUS5KYaAjbHOyUP9lX81ETWU9UxAwpyGgu8XOhNCmQ4WciQGtJ1EPCf3FzA&file_id=00`

Is it possible the URL has been changed?

Awesome work btw!

**Comment by lxr** [comment]
Uploading still works on my machine and on https://gmusic-manager.appspot.com, so that can't be it. I've only ever gotten that error when trying to upload non-MP3 files. Are you sure your file isn't corrupt?

I've just pushed a commit that adds the server's rejection reason to the error string. My guess is that if you try again with the new code, you'll get `session error 503: agent_failure`, which won't help you very much, but it'll at least confirm that your file is triggering the same code path on the server as the malformed files I've experimented with.

**Comment by variab1e** [comment]
Yep, `agent_failure` but the files are valid mp3s to every bit of knowledge I have... Logging on my side->
	INFO: 2015/11/29 08:25:40 mmgr.go:156: 6ce57c499efa649b467997f24ea449d69eaf424a What Else Is There?                 The Understanding              R�yksopp                       0 /0
	\\NAS\home\music/Ripped Music/Röyksopp/The Understanding/07 What Else Is There.mp3
	TRACE: 2015/11/29 08:25:40 mmgr.go:186: postTrack upload to: https://uploadsj.clients.google.com/uploadsj/scottyagent?upload_id=AEnB2Uq7O8vZTSRKbwEXi7l_031HdNVvktBHGCgZ7gar3CqdWIbLXnfj-9-PQ4KE3oN94lpLz4CY61www3Rtn-qSaEIEF6qgDA&file_id=000
	ERROR: 2015/11/29 08:25:41 mmgr.go:162: session error 503: agent_failure

[All my source is here](https://github.com/variab1e/mmgr) - I would think it should be the exact same functionality when it comes to uploading as the samples. Have you ever seen it for any other reason?

**Comment by lxr** [comment]
Aha, got it - you need to seek back to the start of file after reading its checksum and tags. Otherwise, you leave the file pointer at or near the end of the file, and http.Post doesn't actually get to read the whole file. That's why you're getting those errors.

You should also remember to rewind the file between reading its checksum and tags, as tag.Sum likewise leaves the file pointer near the end, where tag.ReadFrom picks off. If you haven't been getting random tag reading errors, your files probably all have fallback ID3v1 tags near the end, but files that don't will trigger spurious tag reading errors.
